server:
  servlet:
    path: /
  port: 0
spring:
  application:
    name: asc
  main:
    banner-mode: log
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:/mapper/xml/**Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: site.niufan.cloud.asc.impl.dal.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0
    # meta-object-handler:
    refresh: true
    #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:logback-${spring.profiles.active}.xml

swagger:
  enabled: true
  title: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://service-registration-center:10000/eureka
    enabled: false