server:
  port: 0
  servlet:
    context-path: /asc
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
security:
  oauth2:
    client:
      client-id: test
      client-secret: 123456
      grant-type: password
      scope: web
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key

